---
vector_config:
  sources:
    our_log:
      type: file
      read_from: beginning
      acknowledgements: null
      ignore_older_secs: 600
      include:
        - /var/log/**/*.log
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - our_log
      database: custom
      endpoint: http://localhost:8123
      table: my_table
      compression: gzip
      healthcheck: false
      skip_unknown_fields: true
